name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build
        run: |
          echo "Installing clang"
          sudo apt install clang -y
          echo "Clang version is:"
          clang --version
          echo "Building all"
          bazel build ... --repo_env=CC=clang --cxxopt=-std=c++17
      - name: Test
        run: |
          bazel test ... --test_output=all --repo_env=CC=clang --cxxopt=-std=c++17
